services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped

    ports:
      - "127.0.0.1:9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus

    depends_on:
      - demo-api


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped

    ports:
      - "127.0.0.1:3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus
      - tempo
      - loki


  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped

    command:
      - "--path.rootfs=/host"

    volumes:
      - /:/host:ro


  alertmanager:
      image: prom/alertmanager
      container_name: alertmanager
      restart: unless-stopped

      ports:
        - "127.0.0.1:9093:9093"

      command:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"

      volumes:
        - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
        - alertmanager_data:/alertmanager

      secrets:
        - slack_webhook_url


  tempo:
    image: grafana/tempo
    container_name: tempo
    restart: unless-stopped

    command:
      - "-config.file=/etc/tempo/tempo.yml"

    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/var/tempo

    ports:
      - "127.0.0.1:3200:3200"


  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped

    command:
      - "-config.file=/etc/loki/loki.yml"

    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml:ro

    ports:
      - "127.0.0.1:3100:3100"


  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    restart: unless-stopped

    command:
      - "--config=/etc/otelcol-contrib/collector.yml"

    volumes:
      - ./otel/collector.yml:/etc/otelcol-contrib/collector.yml:ro
      - app_logs:/var/log/demo-api:ro

    depends_on:
      - tempo
      - loki


  demo-api:
    build:
      context: ./app

    container_name: demo-api
    restart: unless-stopped

    environment:
      OTEL_SERVICE_NAME: demo-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      APP_LOG_PATH: /var/log/demo-api/app.log

    volumes:
      - app_logs:/var/log/demo-api

    ports:
      - "127.0.0.1:8000:8000"

    depends_on:
      - otel-collector


volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  tempo_data:
  app_logs:

secrets:
  slack_webhook_url:
    file: ./.secrets/slack_webhook_url