services:
  prometheus:
    image: prom/prometheus@sha256:69f5241418838263316593f7274a304b095c40bcf22e57272865da91bd60a8ac
    container_name: prometheus
    restart: unless-stopped
    init: true
    read_only: true

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m

    stop_grace_period: 10s

    ports:
      - "127.0.0.1:9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/tests:/etc/prometheus/tests:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus

    depends_on:
      demo-api:
        condition: service_healthy


  grafana:
    image: grafana/grafana@sha256:5dad0df181cb644a14e13617b913b261a54f7d4fd4510721dba420929f35bea2
    container_name: grafana
    restart: unless-stopped

    ports:
      - "127.0.0.1:3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus
      - tempo
      - loki


  node-exporter:
    image: prom/node-exporter@sha256:1b4e4438faca4dd7e001dd445d161a4a2091b0fededa84093b3a8dfeae1f1be0
    container_name: node-exporter
    restart: unless-stopped

    command:
      - "--path.rootfs=/host"

    volumes:
      - /:/host:ro


  alertmanager:
      image: prom/alertmanager@sha256:9e082985f56f4c8c9f724e18f2288c6708f472e56a5286b8863d080434ea065d
      container_name: alertmanager
      restart: unless-stopped

      ports:
        - "127.0.0.1:9093:9093"

      command:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"

      volumes:
        - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
        - alertmanager_data:/alertmanager

      secrets:
        - slack_webhook_url


  tempo:
    image: grafana/tempo@sha256:1ce31d6d7ffab62189685e8c47881d4a561c5d38bd0dbd66e40ca83cef07923d
    container_name: tempo
    restart: unless-stopped

    command:
      - "-config.file=/etc/tempo/tempo.yml"

    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/var/tempo

    ports:
      - "127.0.0.1:3200:3200"


  loki:
    image: grafana/loki@sha256:1107dd5274e0ada47e42472b7a7e71f3b2a2fe878878108f3e2f9e51528f0193
    container_name: loki
    restart: unless-stopped

    command:
      - "-config.file=/etc/loki/loki.yml"

    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml:ro

    ports:
      - "127.0.0.1:3100:3100"


  otel-collector:
    image: otel/opentelemetry-collector-contrib@sha256:fd328de2552466ad78385e1b1289c3f2402b1c45f265b252aab1955b42845ac1
    container_name: otel-collector
    restart: unless-stopped

    command:
      - "--config=/etc/otelcol-contrib/collector.yml"

    volumes:
      - ./otel/collector.yml:/etc/otelcol-contrib/collector.yml:ro
      - app_logs:/var/log/demo-api:ro

    depends_on:
      - tempo
      - loki


  demo-api:
    build:
      context: ./app

    container_name: demo-api
    restart: unless-stopped

    environment:
      OTEL_SERVICE_NAME: demo-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      APP_LOG_PATH: /var/log/demo-api/app.log

    volumes:
      - app_logs:/var/log/demo-api

    ports:
      - "127.0.0.1:8000:8000"

    depends_on:
      - otel-collector


volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  tempo_data:
  app_logs:

secrets:
  slack_webhook_url:
    file: ./.secrets/slack_webhook_url